# Generated by Django 5.0.5 on 2024-05-08 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_cupomdesconto_alter_pedido_data_pedido_cupom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 8, 10, 41, 15, 489336)),
        ),
    ]
